[project]
name = "mc-desktop"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pyserial>=3.5",
    "pyside6>=6.10.0",
]

[project.scripts]
mc-desktop = "mc_desktop.app:run_app"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mc_desktop"]

[tool.setuptools.package-data]
"mc_desktop.resources" = ["Diffnes-Gold.qss"]
