[project]
name = "mc-desktop"
dynamic = ["version"]
description = "This app is providec by National Aperture, Inc. and is used to control their newest line of motion controllers the MC-6 series"
requires-python = ">=3.13"
dependencies = [
    "packaging>=25.0",
    "pyinstaller>=6.16.0",
    "pyserial>=3.5",
    "pyside6>=6.10.0",
    "pytest>=9.0.2",
    "pytest-benchmark>=5.2.3",
    "pytest-qt>=4.5.0",
]

[project.scripts]
mc-desktop = "mc_desktop.app:run_app"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["mc_desktop*"]

[tool.setuptools.dynamic]
version = {attr = "mc_desktop.version.__version__"}

[tool.setuptools.package-data]
"mc_desktop.resources" = ["Diffnes-Gold.qss"]
